### ISSUE TITLE
Update for newer version of renpy? Seems to work less and less with newer builds.

### ISSUE THREAD

**Issue by Vozf** [Kaskadee/rpaextract#2]

**Comment by Kaskadee** [comment]
Can you provide the exact error/exception that is occurring or a sample archive file? 
I haven't tried the program recently, so I'm not sure if the archive format has changed in recent Ren'py builds.

There are also some games that implement their own custom archive compression/encryption that won't work unless implemented in rpaextract.

**Comment by Vozf** [comment]
Sorry, mistook you for another tool with the same name. That bug isn't related to your tool.
Btw tried to use your tool and couldn't with this error, but that's probably something on my side.
```
D:\Downloads\rpaextract-v0.3.1.core>dotnet rpaextract.dll  archive.rpa
Error:
  An assembly specified in the application dependencies manifest (rpaextract.deps.json) was not found:
    package: 'System.Text.Encoding.CodePages', version: '4.5.1'
    path: 'runtimes/win/lib/netcoreapp2.0/System.Text.Encoding.CodePages.dll'
```
The file rpaextract.deps.json is obviously right there in the same folder

**Comment by Kaskadee** [comment]
Well the tool is still using an outdated version of .NET Core, could be related to that.
Since I actually have updated the tool in the past but I just haven't uploaded it here on Github yet, I could update it here too.
